In [2]:

import numpy as np

# Create 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Create 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:

# Addition
add_1d = array_1d + 2
print("Addition (1D):", add_1d)

# Subtraction
sub_1d = array_1d - 2
print("Subtraction (1D):", sub_1d)

# Multiplication
mul_1d = array_1d * 2
print("Multiplication (1D):", mul_1d)

# Division
div_1d = array_1d / 2
print("Division (1D):", div_1d)

Addition (1D): [3 4 5 6 7]
Subtraction (1D): [-1  0  1  2  3]
Multiplication (1D): [ 2  4  6  8 10]
Division (1D): [0.5 1.  1.5 2.  2.5]


In [5]:

# Addition
add_2d = array_2d + 2
print("Addition (2D):\n", add_2d)

# Subtraction
sub_2d = array_2d - 2
print("Subtraction (2D):\n", sub_2d)

# Multiplication
mul_2d = array_2d * 2
print("Multiplication (2D):\n", mul_2d)

# Division
div_2d = array_2d / 2
print("Division (2D):\n", div_2d)

Addition (2D):
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Subtraction (2D):
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
Multiplication (2D):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Division (2D):
 [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [6]:

# Mean
mean_1d = np.mean(array_1d)
print("Mean (1D):", mean_1d)

# Median
median_1d = np.median(array_1d)
print("Median (1D):", median_1d)

# Standard Deviation
std_1d = np.std(array_1d)
print("Standard Deviation (1D):", std_1d)

# Variance
var_1d = np.var(array_1d)
print("Variance (1D):", var_1d)

Mean (1D): 3.0
Median (1D): 3.0
Standard Deviation (1D): 1.4142135623730951
Variance (1D): 2.0


In [7]:

# Mean
mean_2d = np.mean(array_2d)
print("Mean (2D):", mean_2d)

# Median
median_2d = np.median(array_2d)
print("Median (2D):", median_2d)

# Standard Deviation
std_2d = np.std(array_2d)
print("Standard Deviation (2D):", std_2d)

# Variance
var_2d = np.var(array_2d)
print("Variance (2D):", var_2d)

Mean (2D): 5.0
Median (2D): 5.0
Standard Deviation (2D): 2.581988897471611
Variance (2D): 6.666666666666667
