In [1]:
import numpy as np

# Create a 1D NumPy array
arr_1d = np.array([3, 1, 2, 5, 4])


In [2]:
# Accessing elements at specific indices
print(arr_1d[0])   # 3 (accessing the first element)
print(arr_1d[-1])  # 4 (accessing the last element)


3
4


In [3]:
# Slicing: accessing subarrays
print(arr_1d[1:4])   
print(arr_1d[:3])    
print(arr_1d[2:])   


[1 2 5]
[3 1 2]
[2 5 4]


In [4]:
# Sorting the array
sorted_arr = np.sort(arr_1d)
print(sorted_arr)    # [1 2 3 4 5] (sorted array)


[1 2 3 4 5]


In [5]:
# Create a 2D NumPy array
arr_2d = np.array([[3, 1, 2], [5, 4, 6]])


In [6]:
# Accessing elements at specific indices
print(arr_2d[0, 1])   # 1 (accessing element at row 0, column 1)
print(arr_2d[1, 2])   # 6 (accessing element at row 1, column 2)


1
6


In [7]:
# Slicing: accessing subarrays
print(arr_2d[:, 1])   
print(arr_2d[1, :])   # [5 4 6] (second row elements from all columns)
print(arr_2d[:2, :2]) # [[3 1] [5 4]] (subarray of first two rows and columns)


[1 4]
[5 4 6]
[[3 1]
 [5 4]]


In [8]:
# Sorting along an axis
sorted_arr_axis0 = np.sort(arr_2d, axis=0)
print(sorted_arr_axis0)

sorted_arr_axis1 = np.sort(arr_2d, axis=1)
print(sorted_arr_axis1)


[[3 1 2]
 [5 4 6]]
[[1 2 3]
 [4 5 6]]
